### PR TITLE
get working with CNv4

### PR DESCRIPTION
**Pull request by Gingeropolous**
modded pool.js to work moneros new PoW

### CODE REVIEW

**Comment by Gingeropolous** [comment]
ugh i should sqash or something

this adds the config.json example, need to change variant to 13

**Comment by muscleman** [comment]
made a more generic fix to the pool.js. see wownero.json and monero.json config files

**Comment by Gingeropolous** [comment]
awesome, thanks!

**Comment by muscleman** [comment]
thanks for your contribution

**Pull request closed without merging**
