### PR TITLE
More Fixes

### PR DESCRIPTION
**Pull request by croniccorey**
Fixes up some ugliness

@muscleman I am not to sure how to adjust alignment on worker statistics graphs so you may want to have a look at that after.

Live pool with PR merged: https://funwithcrypto.tk/tkts/

### CODE REVIEW

**Comment by croniccorey** [comment]
@muscleman Hold off on merge i'm gonna add 1 or 2 more commits

**Comment by croniccorey** [comment]
@muscleman If you wouldn't mind, id like to find i direct way to chat with you about project.. telegram, skype, or discord.. if you'd be cool with one of those send your contact info via my git email. thanks

**Comment by muscleman** [comment]
https://web.telegram.org/#/im?p=g390944145

**Comment by croniccorey** [comment]
> 
> 
> https://web.telegram.org/#/im?p=g390944145

https://t.me/FunWithCrypto
link did not work.. this is my public channel if yea wanna join and then we can IM

**Comment by croniccorey** [comment]
Done with this PR, Ready for merge.

**Pull request merged**
