### PR TITLE
Cryptonight-R (CNv4) requires block template height argument

### PR DESCRIPTION
**Pull request by BryGuy8913**

### CODE REVIEW

**Comment by muscleman** [comment]
do you also need the algo ?

**Comment by muscleman** [comment]
OIC the confusion

**Comment by BryGuy8913** [comment]
Right, I was just trying to work within the code by massaging the config, but I see your commit you just made at https://github.com/dvandal/cryptonote-nodejs-pool/commit/488a5347dde049f7169311a592b81e6139ecc9dd which is the cleanest way.

Thanks.

**Comment by muscleman** [comment]
thanks for your input

**Pull request closed without merging**
